function null = run_null_calibration(cfg_over)
% RUN_NULL_CALIBRATION  Null distribution of the tau diagnostic on EA data.
%
% WHAT THIS IS
% ------------
% The inferential benchmark ("Leg 2" of CH7_DESIGN.md): with real data there
% is no truth, so the tau heatmap by itself is descriptive.  This routine
% turns it into a calibrated specification test.  Under H0 the euro-area
% data are generated by the VAR(p) estimated on them (posterior mean of
% estimate_bvar_niw), so the VAR-centred prior is correct by construction.
% We simulate R datasets from that null (simulate_fitted_bvar_dgp), run the
% FULL diagnostic pipeline on each (BVAR re-estimated, FMAR lambda
% re-selected, block sampler re-run -- everything the real-data pipeline
% does), and record the block scales.  The output is, per (equation, block):
% null quantiles of the early-horizon mean scale tau_bar, and the null
% frequency with which each block attains the argmax -- i.e. the empirical
% false-positive benchmark of the Ch. 6 reading protocol, now calibrated to
% the EXACT empirical design (K, T, p, persistence, trend).
%
% READING THE OUTPUT AGAINST REAL DATA
% ------------------------------------
%   * A real-data tau_bar(i,g) above null.q95(i,g) is an escape significant
%     at the 5% level in the calibrated sense.
%   * The real-data argmax block in equation i is meaningful only relative
%     to null.argmax_freq(i,:) -- the analogue of the correct-DGP benchmark
%     (0.330 vs 0.976) in the thesis Monte Carlo.
%   * null.maxstat_q95(i) calibrates the pooled "does ANYTHING escape in
%     equation i" flag: max_g tau_bar(i,g) compared to its null 95th
%     percentile (this replaces the retired max/median > 1.5 rule).
%
% USAGE
% -----
%   null = run_null_calibration();                       % defaults below
%   null = run_null_calibration(struct('null', struct('n_rep', 25)));  % quick
%
% CONFIG (cfg.null.*, all defaulted here; cfg_over is merged on top of
% default_config() with cfg.mode = 'fmar')
% ------------------------------------------------------------------------
%   n_rep        200    replications (500 for the thesis run)
%   H            12     horizons simulated/estimated under the null; the
%                       protocol statistic only needs h <= h_early(2), and
%                       cutting H from 48 to 12 cuts runtime ~4x.  Set to
%                       cfg.H for full-heatmap thresholds.
%   h_early      [2 12] horizon window of the tau_bar statistic (monthly
%                       analogue of the Ch. 6 "early-h" window; h = 0, 1
%                       are excluded because the block estimator's h <= 1
%                       is not sampled/is the BVAR).
%   gibbs_n_burn 200    reduced chains for the null reps (the statistic is
%   gibbs_n_keep 300    a posterior MEAN of tau; short chains suffice --
%                       same convention as cfg.mc.* in run_montecarlo).
%   seed         20260901
%   checkpoint_every 10 save results/null_ckpt.mat every so many reps
%   resume       true   continue from a checkpoint if present
%   dataset      'data/ea_dataset.mat'
%   out_mat      'results/null_calibration.mat'
%   out_csv      'results/null_thresholds.csv'
%   sim_method   'resample'
%
% RUNTIME
% -------
% Each replication runs the full FMAR pipeline at K = 5, m = 1 + K*p = 61
% (p = 12), H = 12: BVAR tightness search + 5 x 12 lambda searches + 5 x 12
% Gibbs chains.  Budget roughly 1-3 minutes per rep on a laptop => R = 200
% is an overnight job; ALWAYS do a quick run (n_rep = 10) first and scale
% from the printed per-rep timing.  Checkpointing makes interruption safe.
%
% INTEGRATION ASSUMPTIONS (verify once against the repo; see
% README_EMPIRICAL.md):
%   bvar = estimate_bvar_niw(Y, cfg)
%   blpf = estimate_blp_fmar(Y, cfg, bvar)          -> .lambda (K x H)
%   blpb = estimate_blp_blockadaptive(Y, cfg, bvar, blpf.lambda)
%          -> .tau_mean (K x G x H), .lo/.hi (K x (H+1))

if nargin < 1, cfg_over = struct(); end

cfg = default_config();
cfg.mode = 'fmar';
cfg = merge_struct(cfg, cfg_over);

nd = struct('n_rep', 200, 'H', 12, 'h_early', [2 12], ...
            'gibbs_n_burn', 200, 'gibbs_n_keep', 300, ...
            'seed', 20260901, 'checkpoint_every', 10, 'resume', true, ...
            'dataset', fullfile('data', 'ea_dataset.mat'), ...
            'out_mat', fullfile('results', 'null_calibration.mat'), ...
            'out_csv', fullfile('results', 'null_thresholds.csv'), ...
            'sim_method', 'resample');
if isfield(cfg, 'null'), nd = merge_struct(nd, cfg.null); end
cfg.null = nd;

% --- data and null-run configuration ---------------------------------------
ds = load(cfg.null.dataset);
Y0 = ds.Y;
[T, K] = size(Y0);
if isfield(cfg, 'fmar'), cfg.fmar.isrw = ds.isrw; end   % vectorised patch
cfg.shock_var = 1;
cfg.H = cfg.null.H;
cfg.gibbs.n_burn = cfg.null.gibbs_n_burn;
cfg.gibbs.n_keep = cfg.null.gibbs_n_keep;

fprintf('run_null_calibration: K = %d, T = %d, p = %d, H = %d, R = %d\n', ...
        K, T, cfg.p, cfg.H, cfg.null.n_rep);

% --- the pseudo-true VAR: fitted on the REAL data ---------------------------
rng(cfg.null.seed, 'twister');
bvar0 = estimate_bvar_niw(Y0, cfg);
fprintf('  fitted BVAR: lambda = %.3f, max |eig| = %.4f\n', bvar0.lambda, bvar0.max_eig);

% --- replication loop with checkpointing ------------------------------------
R  = cfg.null.n_rep;
h1 = cfg.null.h_early(1);  h2 = min(cfg.null.h_early(2), cfg.H);
G  = K;                                        % per-variable blocks
tau_all   = nan(R, K, G, cfg.H);               % tau_mean at h = 1..H
cover_all = nan(R, K, cfg.H - 1);              % band coverage of dgp.theta, h >= 2
r0 = 1;

ck = fullfile('results', 'null_ckpt.mat');
if cfg.null.resume && exist(ck, 'file')
    L = load(ck);
    if isequal(L.n_rep, R) && isequal(L.p, cfg.p) && isequal(L.H, cfg.H)
        tau_all = L.tau_all;  cover_all = L.cover_all;  r0 = L.r_done + 1;
        fprintf('  resuming from checkpoint at rep %d\n', r0);
    end
end
if ~exist('results', 'dir'), mkdir('results'); end

t_start = tic;
for r = r0:R
    rng(cfg.null.seed + 1000 * r, 'twister');
    dgp  = simulate_fitted_bvar_dgp(bvar0, Y0, cfg, ...
                                    struct('method', cfg.null.sim_method));
    bvr  = estimate_bvar_niw(dgp.Y, cfg);
    blpf = estimate_blp_fmar(dgp.Y, cfg, bvr);
    blpb = estimate_blp_blockadaptive(dgp.Y, cfg, bvr, blpf.lambda);
    tau_all(r, :, :, :) = blpb.tau_mean;       % (K x G x H)
    th = dgp.theta(:, 3:cfg.H + 1);            % true-under-null IRF, h >= 2
    cover_all(r, :, :) = blpb.lo(:, 3:cfg.H + 1) <= th & ...
                         th <= blpb.hi(:, 3:cfg.H + 1);
    if mod(r, cfg.null.checkpoint_every) == 0 || r == R
        r_done = r; n_rep = R; p = cfg.p; H = cfg.H;                 %#ok<NASGU>
        save(ck, 'tau_all', 'cover_all', 'r_done', 'n_rep', 'p', 'H');
        el = toc(t_start);
        fprintf('  rep %3d / %d done  (%.1f s/rep, ~%.1f min left)\n', ...
                r, R, el / (r - r0 + 1), el / (r - r0 + 1) * (R - r) / 60);
    end
end

% --- statistics --------------------------------------------------------------
% early-horizon mean scale per replication: (R x K x G)
tb = mean(tau_all(:, :, :, h1:h2), 4);

null.q90 = zeros(K, G);  null.q95 = zeros(K, G);  null.q99 = zeros(K, G);
null.tau_bar_mean = squeeze(mean(tb, 1));
null.argmax_freq  = zeros(K, G);
null.maxstat_q95  = zeros(K, 1);
for i = 1:K
    mx = squeeze(max(tb(:, i, :), [], 3));
    q  = empirical_quantile(mx, 0.95);
    null.maxstat_q95(i) = q(1);
    for g = 1:G
        q3 = empirical_quantile(squeeze(tb(:, i, g)), [0.90, 0.95, 0.99]);
        null.q90(i, g) = q3(1);  null.q95(i, g) = q3(2);  null.q99(i, g) = q3(3);
    end
    [~, am] = max(squeeze(tb(:, i, :)), [], 2);
    for g = 1:G
        null.argmax_freq(i, g) = mean(am == g);
    end
end
null.coverage_under_null = squeeze(mean(mean(cover_all, 1), 3));  % per equation
null.h_early = [h1 h2];
null.n_rep = R;  null.p = cfg.p;  null.H = cfg.H;
null.tau_bar_draws = tb;
null.varnames = ds.varnames;

save(cfg.null.out_mat, '-struct', 'null');

% threshold table (long format, thesis Table appendix + reading protocol)
fid = fopen(cfg.null.out_csv, 'w');
fprintf(fid, 'equation,block,null_mean,q90,q95,q99,argmax_freq\n');
for i = 1:K
    for g = 1:G
        fprintf(fid, '%s,%s,%.4f,%.4f,%.4f,%.4f,%.4f\n', ...
                ds.varnames{i}, ds.varnames{g}, null.tau_bar_mean(i, g), ...
                null.q90(i, g), null.q95(i, g), null.q99(i, g), ...
                null.argmax_freq(i, g));
    end
end
fclose(fid);

fprintf('\nrun_null_calibration: done (R = %d).\n', R);
fprintf('  per-equation null argmax frequencies (uniform = %.3f):\n', 1 / G);
for i = 1:K
    fprintf('    eq %-6s: ', ds.varnames{i});
    fprintf('%.3f ', null.argmax_freq(i, :));
    fprintf('| max-stat q95 = %.3f | band coverage under null = %.3f\n', ...
            null.maxstat_q95(i), null.coverage_under_null(i));
end
fprintf('  thresholds written to %s\n', cfg.null.out_csv);
end

% -------------------------------------------------------------------------
function a = merge_struct(a, b)
f = fieldnames(b);
for k = 1:numel(f)
    if isfield(a, f{k}) && isstruct(a.(f{k})) && isstruct(b.(f{k}))
        a.(f{k}) = merge_struct(a.(f{k}), b.(f{k}));
    else
        a.(f{k}) = b.(f{k});
    end
end
end
